### ISSUE TITLE
Mic and speakers don't working

### ISSUE THREAD

**Issue by fxalgrain** [eface2face/rtcninja.js#11]
Hi, 

We have developed a web app using the JsSIP and rtcninja  libraries. And we have noticed the mic and the speakers stop to work when a chrome update is pending. And the only way to solve it is to restart the computer !
The bug has been reproduced multiple times on windows and on mac.

I have open ticket on chromium repository (https://code.google.com/p/chromium/issues/detail?id=467497) but may be it's related to rtcninja library.

I hope you can help use to solve this

**Comment by ibc** [comment]
I'm sorry, but this issue cannot be related to rtcninja at all.

**Comment by fxalgrain** [comment]
Ok thanks
