### ISSUE TITLE
Re-writing SDP (workaround Asterisk bug 22961)

### ISSUE THREAD

**Issue by dpocock** [eface2face/rtcninja.js#17]
JSCommunicator provides a workaround for Asterisk bug 22961, which is useful when mixing and matching different browser versions or older Asterisk versions.

Basically, it mangles the SDP media line like so:

    var new_body = request.body.replace(/ RTP/g, ' UDP/TLS/RTP');

Should this functionality be implemented in RTCNinja instead, with a config option to turn it on/off, maybe with code to detect what the peer expects, so that high level application code doesn't need to worry about such compatibility issues?

**Comment by ibc** [comment]
This will be handled in JsSIP (as it includes the *sdp-transform*  library which parses the SDP and enables easy manipulation):

https://github.com/versatica/JsSIP/issues/320
