### ISSUE TITLE
unsupported constraints

### ISSUE THREAD

**Issue by dpocock** [eface2face/rtcninja.js#18]
If an application tries to use a constraint that the browser doesn't recognise, there is an exception.

Could more logic be added to do one of the following:

- try removing each constraint to see which one causes the error and provide a more verbose log message?
- pro-actively remove constraints that the browser does not support?  E.g. remove goog* constraints if the browser is not Chrome

**Comment by ibc** [comment]
Honestly I do not want to track all the custom constraints each vendor defines and supports.

`rtcninja.browser` exports the [bowser](https://github.com/ded/bowser) module which lets the user detect the current browser and platform.

I understand your concern, but I won't take the responsability of maintaing these exceptions.
