### ISSUE TITLE
Adding support for Microsoft Edge browser released with Windows 10

### ISSUE THREAD

**Issue by mark-veenstra** [eface2face/rtcninja.js#19]
See next article: http://blogs.windows.com/msedgedev/2015/05/13/announcing-media-capture-functionality-in-microsoft-edge/

**Comment by ibc** [comment]
Edge just implements getUserMedia, so not stuff enough for rtcninja, which is supposed to be a complete wrapper/shim for getUserMedia and RTCPeerConnection.

Once Edge is here and adds RTCPeerConnection or ORTC we'll start working to support it. For now there is nothing to do.

**Comment by tilman22** [comment]
Hi Iñaki,

ORTC is now available in Edge: https://blogs.windows.com/msedgedev/2015/09/18/ortc-api-is-now-available-in-microsoft-edge/

Have you already planned to integrate Edge into rtcninja?
There are not yet compatible video codecs between Edge and Firefox/Chrome (are there?). But audio only should work (?). It would also be nice to make audio calls between all browsers.

Tilman

**Comment by saghul** [comment]
> There are not yet compatible video codecs between Edge and Firefox/Chrome (are there?). But audio only should work (?). It would also be nice to make audio calls between all browsers.

Right now audio calls are only supported because Edge implements H264.UC, which is not compatible with vanilla H.264, AFAIK.

**Comment by ibc** [comment]
Edge does not implemente WebRTC 1.0 but ORTC. Currently rtcninja is not supposed to support ORTC.

This will be studied in the future when things become more clear and stable.
