### ISSUE TITLE
rtcninja 2.0 timeline

### ISSUE THREAD

**Issue by mwittig** [eface2face/rtcninja.js#28]
Can you please give me rough timeline about when you plan to release rtcninja 2.0? 
Are you planning to do some kind of beta to get community feedback?

Thanks!

**Comment by ibc** [comment]
Let's say it will be started in January (2016). Hopefully it won't take more than 5-6 weeks.

I will announce it here so users can test it (it will be part of a different branch). Thanks a lot for the help!
