### ISSUE TITLE
problem with parsing SDP

### ISSUE THREAD

**Issue by scgm11** [eface2face/rtcninja.js#35]
I'm not sure is an rtcninja bug but Im getting 

VM368:15 rtcninja:ERROR:RTCPeerConnection setRemoteDescription() | error: +1ms DOMException: Failed to parse SessionDescription. a=fmtp:111 Expects at least 2 fields.

seems like the  new opus_codec by digium is using only fmtp and no other argument as the OS one.

Example:
New: a=fmtp:111
OS: a=fmtp:111 useinbandfec=1

is this an error on the generated SDP? o is ok to have one field for that?

thanks

**Comment by ibc** [comment]
`a=fmtp:111` is useless, it says nothing. If a SDP media section includes a `a=fmtp` line it is supposed to come with, at least, a key/value property into it.

It is the browser's native `setRemoteDescription()` method the one raising such an error. *rtcninja* has nothing to do in here.

Please, report to Asterisk project.

**Comment by jcolp** [comment]
@scgm11 I've created https://issues.asterisk.org/jira/browse/ASTERISK-26520 to track this. Can you attach your configuration and the full signaling so we can determine what is going on?
