### ISSUE TITLE
RTCPeerConnection has no way to set constraints

### ISSUE THREAD

**Issue by nicketson** [eface2face/rtcninja.js#9]
JsSIP exposes an argument "rtcConstraints" which gets passed to the rtcninja.RTCPeerConnection() constructor. RTCPeerConnection deosn't do anything with the argument though.

http://jssip.net/documentation/0.6.x/api/ua/#method_call

**Comment by nicketson** [comment]
--- rtcninja/lib/RTCPeerConnection.js   2015-02-01 17:04:59.000000000 -0500
+++ RTCPeerConnection.js    2015-03-04 13:36:53.862988252 -0500
@@ -34,12 +34,15 @@
 };


-function RTCPeerConnection(pcConfig) {
+function RTCPeerConnection(pcConfig, constraints) {
    debug('new | pcConfig:', pcConfig);

    // Set this.pcConfig and this.options.
    setConfigurationAndOptions.call(this, pcConfig);

+   // Set this.constraints
+   this.constraints = constraints;
+
    // Own version of the localDescription.
    this._localDescription = null;

@@ -403,7 +406,7 @@

 function setPeerConnection() {
    // Create a RTCPeerConnection.
-   this.pc = new Adapter.RTCPeerConnection(this.pcConfig);
+   this.pc = new Adapter.RTCPeerConnection(this.pcConfig, this.constraints);

    // Set RTC events.
    setEvents.call(this);

**Comment by nicketson** [comment]
`--- rtcninja/lib/RTCPeerConnection.js   2015-02-01 17:04:59.000000000 -0500
+++ RTCPeerConnection.js    2015-03-04 13:36:53.862988252 -0500
@@ -34,12 +34,15 @@
 };


-function RTCPeerConnection(pcConfig) {
+function RTCPeerConnection(pcConfig, constraints) {
    debug('new | pcConfig:', pcConfig);

    // Set this.pcConfig and this.options.
    setConfigurationAndOptions.call(this, pcConfig);

+   // Set this.constraints
+   this.constraints = constraints;
+
    // Own version of the localDescription.
    this._localDescription = null;

@@ -403,7 +406,7 @@

 function setPeerConnection() {
    // Create a RTCPeerConnection.
-   this.pc = new Adapter.RTCPeerConnection(this.pcConfig);
+   this.pc = new Adapter.RTCPeerConnection(this.pcConfig, this.constraints);

    // Set RTC events.
    setEvents.call(this);

**Comment by nicketson** [comment]
--- rtcninja/lib/RTCPeerConnection.js   2015-02-01 17:04:59.000000000 -0500
+++ RTCPeerConnection.js    2015-03-04 13:36:53.862988252 -0500
@@ -34,12 +34,15 @@
 };


-function RTCPeerConnection(pcConfig) {
+function RTCPeerConnection(pcConfig, constraints) {
    debug('new | pcConfig:', pcConfig);

    // Set this.pcConfig and this.options.
    setConfigurationAndOptions.call(this, pcConfig);

+   // Set this.constraints
+   this.constraints = constraints;
+
    // Own version of the localDescription.
    this._localDescription = null;

@@ -403,7 +406,7 @@

 function setPeerConnection() {
    // Create a RTCPeerConnection.
-   this.pc = new Adapter.RTCPeerConnection(this.pcConfig);
+   this.pc = new Adapter.RTCPeerConnection(this.pcConfig, this.constraints);

    // Set RTC events.
    setEvents.call(this);

**Comment by ibc** [comment]
The `rtcConstraints` argument in the `RTCPeerConnection` is deprecated in the latest WebRTC draft:

http://www.w3.org/TR/webrtc/#interface-definition

Constraints must be set in `createOffer()` and `createAnswer()`. That's why rtcninja ignores it.
